package controlador;

public class BeanPorta {

    

    public String getCWBC_COTIZACION() {
        return CWBC_COTIZACION;
    }

    public void setCWBC_COTIZACION(String CWBC_COTIZACION) {
        this.CWBC_COTIZACION = CWBC_COTIZACION;
    }

    public String getCWSF_MUELLAJE_COF_IMPORT() {
        return CWSF_MUELLAJE_COF_IMPORT;
    }

    public void setCWSF_MUELLAJE_COF_IMPORT(String CWSF_MUELLAJE_COF_IMPORT) {
        this.CWSF_MUELLAJE_COF_IMPORT = CWSF_MUELLAJE_COF_IMPORT;
    }

    public String getCWSF_MUELLAJE_COF_EXPORT() {
        return CWSF_MUELLAJE_COF_EXPORT;
    }

    public void setCWSF_MUELLAJE_COF_EXPORT(String CWSF_MUELLAJE_COF_EXPORT) {
        this.CWSF_MUELLAJE_COF_EXPORT = CWSF_MUELLAJE_COF_EXPORT;
    }

    public String getCWSF_DESCARGA_LLENOS_GB_VI() {
        return CWSF_DESCARGA_LLENOS_GB_VI;
    }

    public void setCWSF_DESCARGA_LLENOS_GB_VI(String CWSF_DESCARGA_LLENOS_GB_VI) {
        this.CWSF_DESCARGA_LLENOS_GB_VI = CWSF_DESCARGA_LLENOS_GB_VI;
    }

    public String getCWSF_DESCARGA_LLENOS_GB_VD() {
        return CWSF_DESCARGA_LLENOS_GB_VD;
    }

    public void setCWSF_DESCARGA_LLENOS_GB_VD(String CWSF_DESCARGA_LLENOS_GB_VD) {
        this.CWSF_DESCARGA_LLENOS_GB_VD = CWSF_DESCARGA_LLENOS_GB_VD;
    }

    public String getCWSF_DESCARGA_LLENOS_GP_VI() {
        return CWSF_DESCARGA_LLENOS_GP_VI;
    }

    public void setCWSF_DESCARGA_LLENOS_GP_VI(String CWSF_DESCARGA_LLENOS_GP_VI) {
        this.CWSF_DESCARGA_LLENOS_GP_VI = CWSF_DESCARGA_LLENOS_GP_VI;
    }

    public String getCWSF_DESCARGA_LLENOS_GP_VD() {
        return CWSF_DESCARGA_LLENOS_GP_VD;
    }

    public void setCWSF_DESCARGA_LLENOS_GP_VD(String CWSF_DESCARGA_LLENOS_GP_VD) {
        this.CWSF_DESCARGA_LLENOS_GP_VD = CWSF_DESCARGA_LLENOS_GP_VD;
    }

    public String getCWSF_DESCARGA_VACIOS_GB_VI() {
        return CWSF_DESCARGA_VACIOS_GB_VI;
    }

    public void setCWSF_DESCARGA_VACIOS_GB_VI(String CWSF_DESCARGA_VACIOS_GB_VI) {
        this.CWSF_DESCARGA_VACIOS_GB_VI = CWSF_DESCARGA_VACIOS_GB_VI;
    }

    public String getCWSF_DESCARGA_VACIOS_GB_VD() {
        return CWSF_DESCARGA_VACIOS_GB_VD;
    }

    public void setCWSF_DESCARGA_VACIOS_GB_VD(String CWSF_DESCARGA_VACIOS_GB_VD) {
        this.CWSF_DESCARGA_VACIOS_GB_VD = CWSF_DESCARGA_VACIOS_GB_VD;
    }

    public String getCWSF_DESCARGA_VACIOS_GP_VI() {
        return CWSF_DESCARGA_VACIOS_GP_VI;
    }

    public void setCWSF_DESCARGA_VACIOS_GP_VI(String CWSF_DESCARGA_VACIOS_GP_VI) {
        this.CWSF_DESCARGA_VACIOS_GP_VI = CWSF_DESCARGA_VACIOS_GP_VI;
    }

    public String getCWSF_DESCARGA_VACIOS_GP_VD() {
        return CWSF_DESCARGA_VACIOS_GP_VD;
    }

    public void setCWSF_DESCARGA_VACIOS_GP_VD(String CWSF_DESCARGA_VACIOS_GP_VD) {
        this.CWSF_DESCARGA_VACIOS_GP_VD = CWSF_DESCARGA_VACIOS_GP_VD;
    }

    public String getCWSF_CARGA_LLENOS_GB_VI() {
        return CWSF_CARGA_LLENOS_GB_VI;
    }

    public void setCWSF_CARGA_LLENOS_GB_VI(String CWSF_CARGA_LLENOS_GB_VI) {
        this.CWSF_CARGA_LLENOS_GB_VI = CWSF_CARGA_LLENOS_GB_VI;
    }

    public String getCWSF_CARGA_LLENOS_GB_VD() {
        return CWSF_CARGA_LLENOS_GB_VD;
    }

    public void setCWSF_CARGA_LLENOS_GB_VD(String CWSF_CARGA_LLENOS_GB_VD) {
        this.CWSF_CARGA_LLENOS_GB_VD = CWSF_CARGA_LLENOS_GB_VD;
    }

    public String getCWSF_CARGA_LLENOS_GP_VI() {
        return CWSF_CARGA_LLENOS_GP_VI;
    }

    public void setCWSF_CARGA_LLENOS_GP_VI(String CWSF_CARGA_LLENOS_GP_VI) {
        this.CWSF_CARGA_LLENOS_GP_VI = CWSF_CARGA_LLENOS_GP_VI;
    }

    public String getCWSF_CARGA_LLENOS_GP_VD() {
        return CWSF_CARGA_LLENOS_GP_VD;
    }

    public void setCWSF_CARGA_LLENOS_GP_VD(String CWSF_CARGA_LLENOS_GP_VD) {
        this.CWSF_CARGA_LLENOS_GP_VD = CWSF_CARGA_LLENOS_GP_VD;
    }

    public String getCWSF_CARGA_VACIOS_GB_VI() {
        return CWSF_CARGA_VACIOS_GB_VI;
    }

    public void setCWSF_CARGA_VACIOS_GB_VI(String CWSF_CARGA_VACIOS_GB_VI) {
        this.CWSF_CARGA_VACIOS_GB_VI = CWSF_CARGA_VACIOS_GB_VI;
    }

    public String getCWSF_CARGA_VACIOS_GB_VD() {
        return CWSF_CARGA_VACIOS_GB_VD;
    }

    public void setCWSF_CARGA_VACIOS_GB_VD(String CWSF_CARGA_VACIOS_GB_VD) {
        this.CWSF_CARGA_VACIOS_GB_VD = CWSF_CARGA_VACIOS_GB_VD;
    }

    public String getCWSF_CARGA_VACIOS_GP_VI() {
        return CWSF_CARGA_VACIOS_GP_VI;
    }

    public void setCWSF_CARGA_VACIOS_GP_VI(String CWSF_CARGA_VACIOS_GP_VI) {
        this.CWSF_CARGA_VACIOS_GP_VI = CWSF_CARGA_VACIOS_GP_VI;
    }

    public String getCWSF_CARGA_VACIOS_GP_VD() {
        return CWSF_CARGA_VACIOS_GP_VD;
    }

    public void setCWSF_CARGA_VACIOS_GP_VD(String CWSF_CARGA_VACIOS_GP_VD) {
        this.CWSF_CARGA_VACIOS_GP_VD = CWSF_CARGA_VACIOS_GP_VD;
    }

    public String getCWSF_DESCARGA_VEHICULOS_GB() {
        return CWSF_DESCARGA_VEHICULOS_GB;
    }

    public void setCWSF_DESCARGA_VEHICULOS_GB(String CWSF_DESCARGA_VEHICULOS_GB) {
        this.CWSF_DESCARGA_VEHICULOS_GB = CWSF_DESCARGA_VEHICULOS_GB;
    }

    public String getCWSF_DESCARGA_VEHICULOS_GP() {
        return CWSF_DESCARGA_VEHICULOS_GP;
    }

    public void setCWSF_DESCARGA_VEHICULOS_GP(String CWSF_DESCARGA_VEHICULOS_GP) {
        this.CWSF_DESCARGA_VEHICULOS_GP = CWSF_DESCARGA_VEHICULOS_GP;
    }

    public String getCWSF_REESTIBAS_GB() {
        return CWSF_REESTIBAS_GB;
    }

    public void setCWSF_REESTIBAS_GB(String CWSF_REESTIBAS_GB) {
        this.CWSF_REESTIBAS_GB = CWSF_REESTIBAS_GB;
    }

    public String getCWSF_REESTIBAS_GP() {
        return CWSF_REESTIBAS_GP;
    }

    public void setCWSF_REESTIBAS_GP(String CWSF_REESTIBAS_GP) {
        this.CWSF_REESTIBAS_GP = CWSF_REESTIBAS_GP;
    }

    public String getCWSF_TAPA_ESCOTILLAS_GB() {
        return CWSF_TAPA_ESCOTILLAS_GB;
    }

    public void setCWSF_TAPA_ESCOTILLAS_GB(String CWSF_TAPA_ESCOTILLAS_GB) {
        this.CWSF_TAPA_ESCOTILLAS_GB = CWSF_TAPA_ESCOTILLAS_GB;
    }

    public String getCWSF_TAPA_ESCOTILLAS_GP() {
        return CWSF_TAPA_ESCOTILLAS_GP;
    }

    public void setCWSF_TAPA_ESCOTILLAS_GP(String CWSF_TAPA_ESCOTILLAS_GP) {
        this.CWSF_TAPA_ESCOTILLAS_GP = CWSF_TAPA_ESCOTILLAS_GP;
    }

    public String getCWSF_DEPOSITO_TEMP_LLENO_GB() {
        return CWSF_DEPOSITO_TEMP_LLENO_GB;
    }

    public void setCWSF_DEPOSITO_TEMP_LLENO_GB(String CWSF_DEPOSITO_TEMP_LLENO_GB) {
        this.CWSF_DEPOSITO_TEMP_LLENO_GB = CWSF_DEPOSITO_TEMP_LLENO_GB;
    }

    public String getCWSF_DEPOSITO_TEMP_LLENO_GP() {
        return CWSF_DEPOSITO_TEMP_LLENO_GP;
    }

    public void setCWSF_DEPOSITO_TEMP_LLENO_GP(String CWSF_DEPOSITO_TEMP_LLENO_GP) {
        this.CWSF_DEPOSITO_TEMP_LLENO_GP = CWSF_DEPOSITO_TEMP_LLENO_GP;
    }

    public String getCWSF_DEPOSITO_TEMP_VACIO_GB() {
        return CWSF_DEPOSITO_TEMP_VACIO_GB;
    }

    public void setCWSF_DEPOSITO_TEMP_VACIO_GB(String CWSF_DEPOSITO_TEMP_VACIO_GB) {
        this.CWSF_DEPOSITO_TEMP_VACIO_GB = CWSF_DEPOSITO_TEMP_VACIO_GB;
    }

    public String getCWSF_DEPOSITO_TEMP_VACIO_GP() {
        return CWSF_DEPOSITO_TEMP_VACIO_GP;
    }

    public void setCWSF_DEPOSITO_TEMP_VACIO_GP(String CWSF_DEPOSITO_TEMP_VACIO_GP) {
        this.CWSF_DEPOSITO_TEMP_VACIO_GP = CWSF_DEPOSITO_TEMP_VACIO_GP;
    }

    public String getCWSF_REEMBARQUE_LLENO_GB() {
        return CWSF_REEMBARQUE_LLENO_GB;
    }

    public void setCWSF_REEMBARQUE_LLENO_GB(String CWSF_REEMBARQUE_LLENO_GB) {
        this.CWSF_REEMBARQUE_LLENO_GB = CWSF_REEMBARQUE_LLENO_GB;
    }

    public String getCWSF_REEMBARQUE_LLENO_GP() {
        return CWSF_REEMBARQUE_LLENO_GP;
    }

    public void setCWSF_REEMBARQUE_LLENO_GP(String CWSF_REEMBARQUE_LLENO_GP) {
        this.CWSF_REEMBARQUE_LLENO_GP = CWSF_REEMBARQUE_LLENO_GP;
    }

    public String getCWSF_REEMBARQUE_VACIO_GB() {
        return CWSF_REEMBARQUE_VACIO_GB;
    }

    public void setCWSF_REEMBARQUE_VACIO_GB(String CWSF_REEMBARQUE_VACIO_GB) {
        this.CWSF_REEMBARQUE_VACIO_GB = CWSF_REEMBARQUE_VACIO_GB;
    }

    public String getCWSF_REEMBARQUE_VACIO_GP() {
        return CWSF_REEMBARQUE_VACIO_GP;
    }

    public void setCWSF_REEMBARQUE_VACIO_GP(String CWSF_REEMBARQUE_VACIO_GP) {
        this.CWSF_REEMBARQUE_VACIO_GP = CWSF_REEMBARQUE_VACIO_GP;
    }

    public String getCWSF_DEPOSITO_MOMENT_LLENO_GB() {
        return CWSF_DEPOSITO_MOMENT_LLENO_GB;
    }

    public void setCWSF_DEPOSITO_MOMENT_LLENO_GB(String CWSF_DEPOSITO_MOMENT_LLENO_GB) {
        this.CWSF_DEPOSITO_MOMENT_LLENO_GB = CWSF_DEPOSITO_MOMENT_LLENO_GB;
    }

    public String getCWSF_DEPOSITO_MOMENT_LLENO_GP() {
        return CWSF_DEPOSITO_MOMENT_LLENO_GP;
    }

    public void setCWSF_DEPOSITO_MOMENT_LLENO_GP(String CWSF_DEPOSITO_MOMENT_LLENO_GP) {
        this.CWSF_DEPOSITO_MOMENT_LLENO_GP = CWSF_DEPOSITO_MOMENT_LLENO_GP;
    }

    public String getCWSF_DEPOSITO_MOMENT_VACIO_GB() {
        return CWSF_DEPOSITO_MOMENT_VACIO_GB;
    }

    public void setCWSF_DEPOSITO_MOMENT_VACIO_GB(String CWSF_DEPOSITO_MOMENT_VACIO_GB) {
        this.CWSF_DEPOSITO_MOMENT_VACIO_GB = CWSF_DEPOSITO_MOMENT_VACIO_GB;
    }

    public String getCWSF_DEPOSITO_MOMENT_VACIO_GP() {
        return CWSF_DEPOSITO_MOMENT_VACIO_GP;
    }

    public void setCWSF_DEPOSITO_MOMENT_VACIO_GP(String CWSF_DEPOSITO_MOMENT_VACIO_GP) {
        this.CWSF_DEPOSITO_MOMENT_VACIO_GP = CWSF_DEPOSITO_MOMENT_VACIO_GP;
    }

//    public String getCWSF_DESCARGA_MERCA_GB_VD() {
//        return CWSF_DESCARGA_MERCA_GB_VD;
//    }
//
//    public void setCWSF_DESCARGA_MERCA_GB_VD(String CWSF_DESCARGA_MERCA_GB_VD) {
//        this.CWSF_DESCARGA_MERCA_GB_VD = CWSF_DESCARGA_MERCA_GB_VD;
//    }
//
//    public String getCWSF_DESCARGA_MERCA_GB_VI() {
//        return CWSF_DESCARGA_MERCA_GB_VI;
//    }
//
//    public void setCWSF_DESCARGA_MERCA_GB_VI(String CWSF_DESCARGA_MERCA_GB_VI) {
//        this.CWSF_DESCARGA_MERCA_GB_VI = CWSF_DESCARGA_MERCA_GB_VI;
//    }
//
//    public String getCWSF_DESCARGA_MERCA_GP_VD() {
//        return CWSF_DESCARGA_MERCA_GP_VD;
//    }
//
//    public void setCWSF_DESCARGA_MERCA_GP_VD(String CWSF_DESCARGA_MERCA_GP_VD) {
//        this.CWSF_DESCARGA_MERCA_GP_VD = CWSF_DESCARGA_MERCA_GP_VD;
//    }
//
//    public String getCWSF_DESCARGA_MERCA_GP_VI() {
//        return CWSF_DESCARGA_MERCA_GP_VI;
//    }
//
//    public void setCWSF_DESCARGA_MERCA_GP_VI(String CWSF_DESCARGA_MERCA_GP_VI) {
//        this.CWSF_DESCARGA_MERCA_GP_VI = CWSF_DESCARGA_MERCA_GP_VI;
//    }
//
//    public String getCWSF_CARGA_MERCA_GB_VD() {
//        return CWSF_CARGA_MERCA_GB_VD;
//    }
//
//    public void setCWSF_CARGA_MERCA_GB_VD(String CWSF_CARGA_MERCA_GB_VD) {
//        this.CWSF_CARGA_MERCA_GB_VD = CWSF_CARGA_MERCA_GB_VD;
//    }
//
//    public String getCWSF_CARGA_MERCA_GB_VI() {
//        return CWSF_CARGA_MERCA_GB_VI;
//    }
//
//    public void setCWSF_CARGA_MERCA_GB_VI(String CWSF_CARGA_MERCA_GB_VI) {
//        this.CWSF_CARGA_MERCA_GB_VI = CWSF_CARGA_MERCA_GB_VI;
//    }
//
//    public String getCWSF_CARGA_MERCA_GP_VD() {
//        return CWSF_CARGA_MERCA_GP_VD;
//    }
//
//    public void setCWSF_CARGA_MERCA_GP_VD(String CWSF_CARGA_MERCA_GP_VD) {
//        this.CWSF_CARGA_MERCA_GP_VD = CWSF_CARGA_MERCA_GP_VD;
//    }
//
//    public String getCWSF_CARGA_MERCA_GP_VI() {
//        return CWSF_CARGA_MERCA_GP_VI;
//    }
//
//    public void setCWSF_CARGA_MERCA_GP_VI(String CWSF_CARGA_MERCA_GP_VI) {
//        this.CWSF_CARGA_MERCA_GP_VI = CWSF_CARGA_MERCA_GP_VI;
//    }

//    public String getCWSF_CARGA_FRUTA_PALE_GB_VD() {
//        return CWSF_CARGA_FRUTA_PALE_GB_VD;
//    }
//
//    public void setCWSF_CARGA_FRUTA_PALE_GB_VD(String CWSF_CARGA_FRUTA_PALE_GB_VD) {
//        this.CWSF_CARGA_FRUTA_PALE_GB_VD = CWSF_CARGA_FRUTA_PALE_GB_VD;
//    }
//
//    public String getCWSF_CARGA_FRUTA_PALE_GB_VI() {
//        return CWSF_CARGA_FRUTA_PALE_GB_VI;
//    }
//
//    public void setCWSF_CARGA_FRUTA_PALE_GB_VI(String CWSF_CARGA_FRUTA_PALE_GB_VI) {
//        this.CWSF_CARGA_FRUTA_PALE_GB_VI = CWSF_CARGA_FRUTA_PALE_GB_VI;
//    }
//
//    public String getCWSF_CARGA_FRUTA_PALE_GP_VD() {
//        return CWSF_CARGA_FRUTA_PALE_GP_VD;
//    }
//
//    public void setCWSF_CARGA_FRUTA_PALE_GP_VD(String CWSF_CARGA_FRUTA_PALE_GP_VD) {
//        this.CWSF_CARGA_FRUTA_PALE_GP_VD = CWSF_CARGA_FRUTA_PALE_GP_VD;
//    }
//
//    public String getCWSF_CARGA_FRUTA_PALE_GP_VI() {
//        return CWSF_CARGA_FRUTA_PALE_GP_VI;
//    }
//
//    public void setCWSF_CARGA_FRUTA_PALE_GP_VI(String CWSF_CARGA_FRUTA_PALE_GP_VI) {
//        this.CWSF_CARGA_FRUTA_PALE_GP_VI = CWSF_CARGA_FRUTA_PALE_GP_VI;
//    }

    public String getGRABADOR() {
        return GRABADOR;
    }

    public void setGRABADOR(String GRABADOR) {
        this.GRABADOR = GRABADOR;
    }

    public BeanPorta(String CWBC_COTIZACION, String CWSF_MUELLAJE_COF_IMPORT, String CWSF_MUELLAJE_COF_EXPORT, String CWSF_DESCARGA_LLENOS_GB_VI, String CWSF_DESCARGA_LLENOS_GB_VD, String CWSF_DESCARGA_LLENOS_GP_VI,
            String CWSF_DESCARGA_LLENOS_GP_VD, String CWSF_DESCARGA_VACIOS_GB_VI, String CWSF_DESCARGA_VACIOS_GB_VD, String CWSF_DESCARGA_VACIOS_GP_VI, String CWSF_DESCARGA_VACIOS_GP_VD,
            String CWSF_CARGA_LLENOS_GB_VI, String CWSF_CARGA_LLENOS_GB_VD, String CWSF_CARGA_LLENOS_GP_VI, String CWSF_CARGA_LLENOS_GP_VD, String CWSF_CARGA_VACIOS_GB_VI, String CWSF_CARGA_VACIOS_GB_VD, String CWSF_CARGA_VACIOS_GP_VI,
            String CWSF_CARGA_VACIOS_GP_VD, String CWSF_DESCARGA_VEHICULOS_GB, String CWSF_DESCARGA_VEHICULOS_GP, String CWSF_REESTIBAS_GB, String CWSF_REESTIBAS_GP, String CWSF_TAPA_ESCOTILLAS_GB, String CWSF_TAPA_ESCOTILLAS_GP,
            String CWSF_DEPOSITO_TEMP_LLENO_GB, String CWSF_DEPOSITO_TEMP_LLENO_GP, String CWSF_DEPOSITO_TEMP_VACIO_GB, String CWSF_DEPOSITO_TEMP_VACIO_GP, String CWSF_REEMBARQUE_LLENO_GB, String CWSF_REEMBARQUE_LLENO_GP, String CWSF_REEMBARQUE_VACIO_GB,
            String CWSF_REEMBARQUE_VACIO_GP, String CWSF_DEPOSITO_MOMENT_LLENO_GB, String CWSF_DEPOSITO_MOMENT_LLENO_GP, String CWSF_DEPOSITO_MOMENT_VACIO_GB, String CWSF_DEPOSITO_MOMENT_VACIO_GP,
            
            String GRABADOR
    ) {

        this.CWBC_COTIZACION = CWBC_COTIZACION;
        this.CWSF_MUELLAJE_COF_IMPORT = CWSF_MUELLAJE_COF_IMPORT;
        this.CWSF_MUELLAJE_COF_EXPORT = CWSF_MUELLAJE_COF_EXPORT;
        this.CWSF_DESCARGA_LLENOS_GB_VI = CWSF_DESCARGA_LLENOS_GB_VI;
        this.CWSF_DESCARGA_LLENOS_GB_VD = CWSF_DESCARGA_LLENOS_GB_VD;
        this.CWSF_DESCARGA_LLENOS_GP_VI = CWSF_DESCARGA_LLENOS_GP_VI;
        this.CWSF_DESCARGA_LLENOS_GP_VD = CWSF_DESCARGA_LLENOS_GP_VD;
        this.CWSF_DESCARGA_VACIOS_GB_VI = CWSF_DESCARGA_VACIOS_GB_VI;
        this.CWSF_DESCARGA_VACIOS_GB_VD = CWSF_DESCARGA_VACIOS_GB_VD;
        this.CWSF_DESCARGA_VACIOS_GP_VI = CWSF_DESCARGA_VACIOS_GP_VI;
        this.CWSF_DESCARGA_VACIOS_GP_VD = CWSF_DESCARGA_VACIOS_GP_VD;
        this.CWSF_CARGA_LLENOS_GB_VI = CWSF_CARGA_LLENOS_GB_VI;
        this.CWSF_CARGA_LLENOS_GB_VD = CWSF_CARGA_LLENOS_GB_VD;
        this.CWSF_CARGA_LLENOS_GP_VI = CWSF_CARGA_LLENOS_GP_VI;
        this.CWSF_CARGA_LLENOS_GP_VD = CWSF_CARGA_LLENOS_GP_VD;
        this.CWSF_CARGA_VACIOS_GB_VI = CWSF_CARGA_VACIOS_GB_VI;
        this.CWSF_CARGA_VACIOS_GB_VD = CWSF_CARGA_VACIOS_GB_VD;
        this.CWSF_CARGA_VACIOS_GP_VI = CWSF_CARGA_VACIOS_GP_VI;
        this.CWSF_CARGA_VACIOS_GP_VD = CWSF_CARGA_VACIOS_GP_VD;
        this.CWSF_DESCARGA_VEHICULOS_GB = CWSF_DESCARGA_VEHICULOS_GB;
        this.CWSF_DESCARGA_VEHICULOS_GP = CWSF_DESCARGA_VEHICULOS_GP;
        this.CWSF_REESTIBAS_GB = CWSF_REESTIBAS_GB;
        this.CWSF_REESTIBAS_GP = CWSF_REESTIBAS_GP;
        this.CWSF_TAPA_ESCOTILLAS_GB = CWSF_TAPA_ESCOTILLAS_GB;
        this.CWSF_TAPA_ESCOTILLAS_GP = CWSF_TAPA_ESCOTILLAS_GP;
        this.CWSF_DEPOSITO_TEMP_LLENO_GB = CWSF_DEPOSITO_TEMP_LLENO_GB;
        this.CWSF_DEPOSITO_TEMP_LLENO_GP = CWSF_DEPOSITO_TEMP_LLENO_GP;
        this.CWSF_DEPOSITO_TEMP_VACIO_GB = CWSF_DEPOSITO_TEMP_VACIO_GB;
        this.CWSF_DEPOSITO_TEMP_VACIO_GP = CWSF_DEPOSITO_TEMP_VACIO_GP;
        this.CWSF_REEMBARQUE_LLENO_GB = CWSF_REEMBARQUE_LLENO_GB;
        this.CWSF_REEMBARQUE_LLENO_GP = CWSF_REEMBARQUE_LLENO_GP;
        this.CWSF_REEMBARQUE_VACIO_GB = CWSF_REEMBARQUE_VACIO_GB;
        this.CWSF_REEMBARQUE_VACIO_GP = CWSF_REEMBARQUE_VACIO_GP;
        this.CWSF_DEPOSITO_MOMENT_LLENO_GB = CWSF_DEPOSITO_MOMENT_LLENO_GB;
        this.CWSF_DEPOSITO_MOMENT_LLENO_GP = CWSF_DEPOSITO_MOMENT_LLENO_GP;
        this.CWSF_DEPOSITO_MOMENT_VACIO_GB = CWSF_DEPOSITO_MOMENT_VACIO_GB;
        this.CWSF_DEPOSITO_MOMENT_VACIO_GP = CWSF_DEPOSITO_MOMENT_VACIO_GP;
        this.GRABADOR = GRABADOR;

    }
    
  

    private String CWBC_COTIZACION;
    private String CWSF_MUELLAJE_COF_IMPORT;
    private String CWSF_MUELLAJE_COF_EXPORT;
    private String CWSF_DESCARGA_LLENOS_GB_VI;
    private String CWSF_DESCARGA_LLENOS_GB_VD;
    private String CWSF_DESCARGA_LLENOS_GP_VI;
    private String CWSF_DESCARGA_LLENOS_GP_VD;
    private String CWSF_DESCARGA_VACIOS_GB_VI;
    private String CWSF_DESCARGA_VACIOS_GB_VD;
    private String CWSF_DESCARGA_VACIOS_GP_VI;
    private String CWSF_DESCARGA_VACIOS_GP_VD;
    private String CWSF_CARGA_LLENOS_GB_VI;
    private String CWSF_CARGA_LLENOS_GB_VD;
    private String CWSF_CARGA_LLENOS_GP_VI;
    private String CWSF_CARGA_LLENOS_GP_VD;
    private String CWSF_CARGA_VACIOS_GB_VI;
    private String CWSF_CARGA_VACIOS_GB_VD;
    private String CWSF_CARGA_VACIOS_GP_VI;
    private String CWSF_CARGA_VACIOS_GP_VD;
    private String CWSF_DESCARGA_VEHICULOS_GB;
    private String CWSF_DESCARGA_VEHICULOS_GP;
    private String CWSF_REESTIBAS_GB;
    private String CWSF_REESTIBAS_GP;
    private String CWSF_TAPA_ESCOTILLAS_GB;
    private String CWSF_TAPA_ESCOTILLAS_GP;
    private String CWSF_DEPOSITO_TEMP_LLENO_GB;
    private String CWSF_DEPOSITO_TEMP_LLENO_GP;
    private String CWSF_DEPOSITO_TEMP_VACIO_GB;
    private String CWSF_DEPOSITO_TEMP_VACIO_GP;
    private String CWSF_REEMBARQUE_LLENO_GB;
    private String CWSF_REEMBARQUE_LLENO_GP;
    private String CWSF_REEMBARQUE_VACIO_GB;
    private String CWSF_REEMBARQUE_VACIO_GP;
    private String CWSF_DEPOSITO_MOMENT_LLENO_GB;
    private String CWSF_DEPOSITO_MOMENT_LLENO_GP;
    private String CWSF_DEPOSITO_MOMENT_VACIO_GB;
    private String CWSF_DEPOSITO_MOMENT_VACIO_GP;
    private String GRABADOR;

    public BeanPorta() {
    }

}
