package controlador;

public class BeanPorta {

    
    
    
    public String getCWBC_COTIZACION() {
        return CWBC_COTIZACION;
    }

    public void setCWBC_COTIZACION(String CWBC_COTIZACION) {
        this.CWBC_COTIZACION = CWBC_COTIZACION;
    }

    public String getCWSF_MUELLAJE_COF_IMPORT() {
        return CWSF_MUELLAJE_COF_IMPORT;
    }

    public void setCWSF_MUELLAJE_COF_IMPORT(String CWSF_MUELLAJE_COF_IMPORT) {
        this.CWSF_MUELLAJE_COF_IMPORT = CWSF_MUELLAJE_COF_IMPORT;
    }

    public String getCWSF_MUELLAJE_COF_EXPORT() {
        return CWSF_MUELLAJE_COF_EXPORT;
    }

    public void setCWSF_MUELLAJE_COF_EXPORT(String CWSF_MUELLAJE_COF_EXPORT) {
        this.CWSF_MUELLAJE_COF_EXPORT = CWSF_MUELLAJE_COF_EXPORT;
    }

    public String getCWSF_DESCARGA_LLENOS_GB_VI() {
        return CWSF_DESCARGA_LLENOS_GB_VI;
    }

    public void setCWSF_DESCARGA_LLENOS_GB_VI(String CWSF_DESCARGA_LLENOS_GB_VI) {
        this.CWSF_DESCARGA_LLENOS_GB_VI = CWSF_DESCARGA_LLENOS_GB_VI;
    }

    public String getCWSF_DESCARGA_LLENOS_GB_VD() {
        return CWSF_DESCARGA_LLENOS_GB_VD;
    }

    public void setCWSF_DESCARGA_LLENOS_GB_VD(String CWSF_DESCARGA_LLENOS_GB_VD) {
        this.CWSF_DESCARGA_LLENOS_GB_VD = CWSF_DESCARGA_LLENOS_GB_VD;
    }

    public String getCWSF_DESCARGA_LLENOS_GP_VI() {
        return CWSF_DESCARGA_LLENOS_GP_VI;
    }

    public void setCWSF_DESCARGA_LLENOS_GP_VI(String CWSF_DESCARGA_LLENOS_GP_VI) {
        this.CWSF_DESCARGA_LLENOS_GP_VI = CWSF_DESCARGA_LLENOS_GP_VI;
    }

    public String getCWSF_DESCARGA_LLENOS_GP_VD() {
        return CWSF_DESCARGA_LLENOS_GP_VD;
    }

    public void setCWSF_DESCARGA_LLENOS_GP_VD(String CWSF_DESCARGA_LLENOS_GP_VD) {
        this.CWSF_DESCARGA_LLENOS_GP_VD = CWSF_DESCARGA_LLENOS_GP_VD;
    }

    public String getCWSF_DESCARGA_VACIOS_GB_VI() {
        return CWSF_DESCARGA_VACIOS_GB_VI;
    }

    public void setCWSF_DESCARGA_VACIOS_GB_VI(String CWSF_DESCARGA_VACIOS_GB_VI) {
        this.CWSF_DESCARGA_VACIOS_GB_VI = CWSF_DESCARGA_VACIOS_GB_VI;
    }

    public String getCWSF_DESCARGA_VACIOS_GB_VD() {
        return CWSF_DESCARGA_VACIOS_GB_VD;
    }

    public void setCWSF_DESCARGA_VACIOS_GB_VD(String CWSF_DESCARGA_VACIOS_GB_VD) {
        this.CWSF_DESCARGA_VACIOS_GB_VD = CWSF_DESCARGA_VACIOS_GB_VD;
    }

    public String getCWSF_DESCARGA_VACIOS_GP_VI() {
        return CWSF_DESCARGA_VACIOS_GP_VI;
    }

    public void setCWSF_DESCARGA_VACIOS_GP_VI(String CWSF_DESCARGA_VACIOS_GP_VI) {
        this.CWSF_DESCARGA_VACIOS_GP_VI = CWSF_DESCARGA_VACIOS_GP_VI;
    }

    public String getCWSF_DESCARGA_VACIOS_GP_VD() {
        return CWSF_DESCARGA_VACIOS_GP_VD;
    }

    public void setCWSF_DESCARGA_VACIOS_GP_VD(String CWSF_DESCARGA_VACIOS_GP_VD) {
        this.CWSF_DESCARGA_VACIOS_GP_VD = CWSF_DESCARGA_VACIOS_GP_VD;
    }

    public String getCWSF_CARGA_LLENOS_GB_VI() {
        return CWSF_CARGA_LLENOS_GB_VI;
    }

    public void setCWSF_CARGA_LLENOS_GB_VI(String CWSF_CARGA_LLENOS_GB_VI) {
        this.CWSF_CARGA_LLENOS_GB_VI = CWSF_CARGA_LLENOS_GB_VI;
    }

    public String getCWSF_CARGA_LLENOS_GB_VD() {
        return CWSF_CARGA_LLENOS_GB_VD;
    }

    public void setCWSF_CARGA_LLENOS_GB_VD(String CWSF_CARGA_LLENOS_GB_VD) {
        this.CWSF_CARGA_LLENOS_GB_VD = CWSF_CARGA_LLENOS_GB_VD;
    }

    public String getCWSF_CARGA_LLENOS_GP_VI() {
        return CWSF_CARGA_LLENOS_GP_VI;
    }

    public void setCWSF_CARGA_LLENOS_GP_VI(String CWSF_CARGA_LLENOS_GP_VI) {
        this.CWSF_CARGA_LLENOS_GP_VI = CWSF_CARGA_LLENOS_GP_VI;
    }

    public String getCWSF_CARGA_LLENOS_GP_VD() {
        return CWSF_CARGA_LLENOS_GP_VD;
    }

    public void setCWSF_CARGA_LLENOS_GP_VD(String CWSF_CARGA_LLENOS_GP_VD) {
        this.CWSF_CARGA_LLENOS_GP_VD = CWSF_CARGA_LLENOS_GP_VD;
    }

    public String getCWSF_CARGA_VACIOS_GB_VI() {
        return CWSF_CARGA_VACIOS_GB_VI;
    }

    public void setCWSF_CARGA_VACIOS_GB_VI(String CWSF_CARGA_VACIOS_GB_VI) {
        this.CWSF_CARGA_VACIOS_GB_VI = CWSF_CARGA_VACIOS_GB_VI;
    }

    public String getCWSF_CARGA_VACIOS_GB_VD() {
        return CWSF_CARGA_VACIOS_GB_VD;
    }

    public void setCWSF_CARGA_VACIOS_GB_VD(String CWSF_CARGA_VACIOS_GB_VD) {
        this.CWSF_CARGA_VACIOS_GB_VD = CWSF_CARGA_VACIOS_GB_VD;
    }

    public String getCWSF_CARGA_VACIOS_GP_VI() {
        return CWSF_CARGA_VACIOS_GP_VI;
    }

    public void setCWSF_CARGA_VACIOS_GP_VI(String CWSF_CARGA_VACIOS_GP_VI) {
        this.CWSF_CARGA_VACIOS_GP_VI = CWSF_CARGA_VACIOS_GP_VI;
    }

    public String getCWSF_CARGA_VACIOS_GP_VD() {
        return CWSF_CARGA_VACIOS_GP_VD;
    }

    public void setCWSF_CARGA_VACIOS_GP_VD(String CWSF_CARGA_VACIOS_GP_VD) {
        this.CWSF_CARGA_VACIOS_GP_VD = CWSF_CARGA_VACIOS_GP_VD;
    }

    public String getCWSF_DESCARGA_VEHICULOS_GB() {
        return CWSF_DESCARGA_VEHICULOS_GB;
    }

    public void setCWSF_DESCARGA_VEHICULOS_GB(String CWSF_DESCARGA_VEHICULOS_GB) {
        this.CWSF_DESCARGA_VEHICULOS_GB = CWSF_DESCARGA_VEHICULOS_GB;
    }

    public String getCWSF_DESCARGA_VEHICULOS_GP() {
        return CWSF_DESCARGA_VEHICULOS_GP;
    }

    public void setCWSF_DESCARGA_VEHICULOS_GP(String CWSF_DESCARGA_VEHICULOS_GP) {
        this.CWSF_DESCARGA_VEHICULOS_GP = CWSF_DESCARGA_VEHICULOS_GP;
    }

    public String getCWSF_REESTIBAS_GB() {
        return CWSF_REESTIBAS_GB;
    }

    public void setCWSF_REESTIBAS_GB(String CWSF_REESTIBAS_GB) {
        this.CWSF_REESTIBAS_GB = CWSF_REESTIBAS_GB;
    }

    public String getCWSF_REESTIBAS_GP() {
        return CWSF_REESTIBAS_GP;
    }

    public void setCWSF_REESTIBAS_GP(String CWSF_REESTIBAS_GP) {
        this.CWSF_REESTIBAS_GP = CWSF_REESTIBAS_GP;
    }

    public String getCWSF_TAPA_ESCOTILLAS_GB() {
        return CWSF_TAPA_ESCOTILLAS_GB;
    }

    public void setCWSF_TAPA_ESCOTILLAS_GB(String CWSF_TAPA_ESCOTILLAS_GB) {
        this.CWSF_TAPA_ESCOTILLAS_GB = CWSF_TAPA_ESCOTILLAS_GB;
    }

    public String getCWSF_TAPA_ESCOTILLAS_GP() {
        return CWSF_TAPA_ESCOTILLAS_GP;
    }

    public void setCWSF_TAPA_ESCOTILLAS_GP(String CWSF_TAPA_ESCOTILLAS_GP) {
        this.CWSF_TAPA_ESCOTILLAS_GP = CWSF_TAPA_ESCOTILLAS_GP;
    }

    public String getCWSF_DEPOSITO_TEMP_LLENO_GB() {
        return CWSF_DEPOSITO_TEMP_LLENO_GB;
    }

    public void setCWSF_DEPOSITO_TEMP_LLENO_GB(String CWSF_DEPOSITO_TEMP_LLENO_GB) {
        this.CWSF_DEPOSITO_TEMP_LLENO_GB = CWSF_DEPOSITO_TEMP_LLENO_GB;
    }

    public String getCWSF_DEPOSITO_TEMP_LLENO_GP() {
        return CWSF_DEPOSITO_TEMP_LLENO_GP;
    }

    public void setCWSF_DEPOSITO_TEMP_LLENO_GP(String CWSF_DEPOSITO_TEMP_LLENO_GP) {
        this.CWSF_DEPOSITO_TEMP_LLENO_GP = CWSF_DEPOSITO_TEMP_LLENO_GP;
    }

    public String getCWSF_DEPOSITO_TEMP_VACIO_GB() {
        return CWSF_DEPOSITO_TEMP_VACIO_GB;
    }

    public void setCWSF_DEPOSITO_TEMP_VACIO_GB(String CWSF_DEPOSITO_TEMP_VACIO_GB) {
        this.CWSF_DEPOSITO_TEMP_VACIO_GB = CWSF_DEPOSITO_TEMP_VACIO_GB;
    }

    public String getCWSF_DEPOSITO_TEMP_VACIO_GP() {
        return CWSF_DEPOSITO_TEMP_VACIO_GP;
    }

    public void setCWSF_DEPOSITO_TEMP_VACIO_GP(String CWSF_DEPOSITO_TEMP_VACIO_GP) {
        this.CWSF_DEPOSITO_TEMP_VACIO_GP = CWSF_DEPOSITO_TEMP_VACIO_GP;
    }

    public String getCWSF_REEMBARQUE_LLENO_GB() {
        return CWSF_REEMBARQUE_LLENO_GB;
    }

    public void setCWSF_REEMBARQUE_LLENO_GB(String CWSF_REEMBARQUE_LLENO_GB) {
        this.CWSF_REEMBARQUE_LLENO_GB = CWSF_REEMBARQUE_LLENO_GB;
    }

    public String getCWSF_REEMBARQUE_LLENO_GP() {
        return CWSF_REEMBARQUE_LLENO_GP;
    }

    public void setCWSF_REEMBARQUE_LLENO_GP(String CWSF_REEMBARQUE_LLENO_GP) {
        this.CWSF_REEMBARQUE_LLENO_GP = CWSF_REEMBARQUE_LLENO_GP;
    }

    public String getCWSF_REEMBARQUE_VACIO_GB() {
        return CWSF_REEMBARQUE_VACIO_GB;
    }

    public void setCWSF_REEMBARQUE_VACIO_GB(String CWSF_REEMBARQUE_VACIO_GB) {
        this.CWSF_REEMBARQUE_VACIO_GB = CWSF_REEMBARQUE_VACIO_GB;
    }

    public String getCWSF_REEMBARQUE_VACIO_GP() {
        return CWSF_REEMBARQUE_VACIO_GP;
    }

    public void setCWSF_REEMBARQUE_VACIO_GP(String CWSF_REEMBARQUE_VACIO_GP) {
        this.CWSF_REEMBARQUE_VACIO_GP = CWSF_REEMBARQUE_VACIO_GP;
    }

    public String getGRABADOR() {
        return GRABADOR;
    }

    public void setGRABADOR(String GRABADOR) {
        this.GRABADOR = GRABADOR;
    }

    public String getCWSF_DEPOSITO_MOMENT_GP() {
        return CWSF_DEPOSITO_MOMENT_GP;
    }

    public void setCWSF_DEPOSITO_MOMENT_GP(String CWSF_DEPOSITO_MOMENT_GP) {
        this.CWSF_DEPOSITO_MOMENT_GP = CWSF_DEPOSITO_MOMENT_GP;
    }

    public String getCWSF_DEPOSITO_MOMENT_GB() {
        return CWSF_DEPOSITO_MOMENT_GB;
    }

    public void setCWSF_DEPOSITO_MOMENT_GB(String CWSF_DEPOSITO_MOMENT_GB) {
        this.CWSF_DEPOSITO_MOMENT_GB = CWSF_DEPOSITO_MOMENT_GB;
    }

    public String getGRABADOR_FECHA() {
        return GRABADOR_FECHA;
    }

    public void setGRABADOR_FECHA(String GRABADOR_FECHA) {
        this.GRABADOR_FECHA = GRABADOR_FECHA;
    }

    public String getACTUALIZADOR() {
        return ACTUALIZADOR;
    }

    public void setACTUALIZADOR(String ACTUALIZADOR) {
        this.ACTUALIZADOR = ACTUALIZADOR;
    }

    public String getACTUALIZADOR_FECHA() {
        return ACTUALIZADOR_FECHA;
    }

    public void setACTUALIZADOR_FECHA(String ACTUALIZADOR_FECHA) {
        this.ACTUALIZADOR_FECHA = ACTUALIZADOR_FECHA;
    }

    public String getCWSF_REEMBARQUE_LLENO_RF_GP() {
        return CWSF_REEMBARQUE_LLENO_RF_GP;
    }

    public void setCWSF_REEMBARQUE_LLENO_RF_GP(String CWSF_REEMBARQUE_LLENO_RF_GP) {
        this.CWSF_REEMBARQUE_LLENO_RF_GP = CWSF_REEMBARQUE_LLENO_RF_GP;
    }

    public String getCWSF_REEMBARQUE_LLENO_RF_GB() {
        return CWSF_REEMBARQUE_LLENO_RF_GB;
    }

    public void setCWSF_REEMBARQUE_LLENO_RF_GB(String CWSF_REEMBARQUE_LLENO_RF_GB) {
        this.CWSF_REEMBARQUE_LLENO_RF_GB = CWSF_REEMBARQUE_LLENO_RF_GB;
    }

    public String getCWBC_HORA() {
        return CWBC_HORA;
    }

    public void setCWBC_HORA(String CWBC_HORA) {
        this.CWBC_HORA = CWBC_HORA;
    }

    public String getCWBC_ETA() {
        return CWBC_ETA;
    }

    public void setCWBC_ETA(String CWBC_ETA) {
        this.CWBC_ETA = CWBC_ETA;
    }

    public String getTON_IMPORT() {
        return TON_IMPORT;
    }

    public void setTON_IMPORT(String TON_IMPORT) {
        this.TON_IMPORT = TON_IMPORT;
    }

    public String getTON_EXPORT() {
        return TON_EXPORT;
    }

    public void setTON_EXPORT(String TON_EXPORT) {
        this.TON_EXPORT = TON_EXPORT;
    }
    
    
    

    public BeanPorta(String CWBC_COTIZACION, 
            String CWSF_MUELLAJE_COF_IMPORT, String CWSF_MUELLAJE_COF_EXPORT, 
            String CWSF_DESCARGA_LLENOS_GB_VI, String CWSF_DESCARGA_LLENOS_GB_VD, String CWSF_DESCARGA_LLENOS_GP_VI, String CWSF_DESCARGA_LLENOS_GP_VD, 
            String CWSF_DESCARGA_VACIOS_GB_VI, String CWSF_DESCARGA_VACIOS_GB_VD, String CWSF_DESCARGA_VACIOS_GP_VI, String CWSF_DESCARGA_VACIOS_GP_VD,
            String CWSF_CARGA_LLENOS_GB_VI, String CWSF_CARGA_LLENOS_GB_VD, String CWSF_CARGA_LLENOS_GP_VI, String CWSF_CARGA_LLENOS_GP_VD, 
            String CWSF_CARGA_VACIOS_GB_VI, String CWSF_CARGA_VACIOS_GB_VD, String CWSF_CARGA_VACIOS_GP_VI,String CWSF_CARGA_VACIOS_GP_VD, 
            String CWSF_DESCARGA_VEHICULOS_GB, String CWSF_DESCARGA_VEHICULOS_GP, 
            String CWSF_REESTIBAS_GB, String CWSF_REESTIBAS_GP, 
            String CWSF_TAPA_ESCOTILLAS_GB, String CWSF_TAPA_ESCOTILLAS_GP,
            String CWSF_DEPOSITO_TEMP_LLENO_GB, String CWSF_DEPOSITO_TEMP_LLENO_GP, String CWSF_DEPOSITO_TEMP_VACIO_GB, String CWSF_DEPOSITO_TEMP_VACIO_GP, 
            String CWSF_REEMBARQUE_LLENO_GB, String CWSF_REEMBARQUE_LLENO_RF_GB, String CWSF_REEMBARQUE_LLENO_GP,  String CWSF_REEMBARQUE_LLENO_RF_GP,
            String CWSF_REEMBARQUE_VACIO_GB,
            String CWSF_REEMBARQUE_VACIO_GP,
            String CWSF_DEPOSITO_MOMENT_GP, String CWSF_DEPOSITO_MOMENT_GB,
            String GRABADOR, String GRABADOR_FECHA,
            String TON_IMPORT,
            String TON_EXPORT
             
    ) {

        this.CWBC_COTIZACION = CWBC_COTIZACION;
        this.CWSF_MUELLAJE_COF_IMPORT = CWSF_MUELLAJE_COF_IMPORT;
        this.CWSF_MUELLAJE_COF_EXPORT = CWSF_MUELLAJE_COF_EXPORT;
        this.CWSF_DESCARGA_LLENOS_GB_VI = CWSF_DESCARGA_LLENOS_GB_VI;
        this.CWSF_DESCARGA_LLENOS_GB_VD = CWSF_DESCARGA_LLENOS_GB_VD;
        this.CWSF_DESCARGA_LLENOS_GP_VI = CWSF_DESCARGA_LLENOS_GP_VI;
        this.CWSF_DESCARGA_LLENOS_GP_VD = CWSF_DESCARGA_LLENOS_GP_VD;
        this.CWSF_DESCARGA_VACIOS_GB_VI = CWSF_DESCARGA_VACIOS_GB_VI;
        this.CWSF_DESCARGA_VACIOS_GB_VD = CWSF_DESCARGA_VACIOS_GB_VD;
        this.CWSF_DESCARGA_VACIOS_GP_VI = CWSF_DESCARGA_VACIOS_GP_VI;
        this.CWSF_DESCARGA_VACIOS_GP_VD = CWSF_DESCARGA_VACIOS_GP_VD;
        this.CWSF_CARGA_LLENOS_GB_VI = CWSF_CARGA_LLENOS_GB_VI;
        this.CWSF_CARGA_LLENOS_GB_VD = CWSF_CARGA_LLENOS_GB_VD;
        this.CWSF_CARGA_LLENOS_GP_VI = CWSF_CARGA_LLENOS_GP_VI;
        this.CWSF_CARGA_LLENOS_GP_VD = CWSF_CARGA_LLENOS_GP_VD;
        this.CWSF_CARGA_VACIOS_GB_VI = CWSF_CARGA_VACIOS_GB_VI;
        this.CWSF_CARGA_VACIOS_GB_VD = CWSF_CARGA_VACIOS_GB_VD;
        this.CWSF_CARGA_VACIOS_GP_VI = CWSF_CARGA_VACIOS_GP_VI;
        this.CWSF_CARGA_VACIOS_GP_VD = CWSF_CARGA_VACIOS_GP_VD;
        this.CWSF_DESCARGA_VEHICULOS_GB = CWSF_DESCARGA_VEHICULOS_GB;
        this.CWSF_DESCARGA_VEHICULOS_GP = CWSF_DESCARGA_VEHICULOS_GP;
        this.CWSF_REESTIBAS_GB = CWSF_REESTIBAS_GB;
        this.CWSF_REESTIBAS_GP = CWSF_REESTIBAS_GP;
        this.CWSF_TAPA_ESCOTILLAS_GB = CWSF_TAPA_ESCOTILLAS_GB;
        this.CWSF_TAPA_ESCOTILLAS_GP = CWSF_TAPA_ESCOTILLAS_GP;
        this.CWSF_DEPOSITO_TEMP_LLENO_GB = CWSF_DEPOSITO_TEMP_LLENO_GB;
        this.CWSF_DEPOSITO_TEMP_LLENO_GP = CWSF_DEPOSITO_TEMP_LLENO_GP;
        this.CWSF_DEPOSITO_TEMP_VACIO_GB = CWSF_DEPOSITO_TEMP_VACIO_GB;
        this.CWSF_DEPOSITO_TEMP_VACIO_GP = CWSF_DEPOSITO_TEMP_VACIO_GP;
        this.CWSF_REEMBARQUE_LLENO_GB = CWSF_REEMBARQUE_LLENO_GB;
        this.CWSF_REEMBARQUE_LLENO_GP = CWSF_REEMBARQUE_LLENO_GP;
        this.CWSF_REEMBARQUE_VACIO_GB = CWSF_REEMBARQUE_VACIO_GB;
        this.CWSF_REEMBARQUE_VACIO_GP = CWSF_REEMBARQUE_VACIO_GP;
        this.CWSF_DEPOSITO_MOMENT_GP = CWSF_DEPOSITO_MOMENT_GP;
        this.CWSF_DEPOSITO_MOMENT_GB = CWSF_DEPOSITO_MOMENT_GB;
        this.GRABADOR = GRABADOR;
        this.GRABADOR_FECHA = GRABADOR_FECHA;
        this.CWSF_REEMBARQUE_LLENO_RF_GP = CWSF_REEMBARQUE_LLENO_RF_GP;
        this.CWSF_REEMBARQUE_LLENO_RF_GB = CWSF_REEMBARQUE_LLENO_RF_GB;
        this.TON_IMPORT = TON_IMPORT;
        this.TON_EXPORT = TON_EXPORT;

    }

    private String CWBC_COTIZACION;
    private String CWBC_HORA;
    private String CWBC_ETA;
    private String CWSF_MUELLAJE_COF_IMPORT;
    private String CWSF_MUELLAJE_COF_EXPORT;
    private String CWSF_DESCARGA_LLENOS_GB_VI;
    private String CWSF_DESCARGA_LLENOS_GB_VD;
    private String CWSF_DESCARGA_LLENOS_GP_VI;
    private String CWSF_DESCARGA_LLENOS_GP_VD;
    private String CWSF_DESCARGA_VACIOS_GB_VI;
    private String CWSF_DESCARGA_VACIOS_GB_VD;
    private String CWSF_DESCARGA_VACIOS_GP_VI;
    private String CWSF_DESCARGA_VACIOS_GP_VD;
    private String CWSF_CARGA_LLENOS_GB_VI;
    private String CWSF_CARGA_LLENOS_GB_VD;
    private String CWSF_CARGA_LLENOS_GP_VI;
    private String CWSF_CARGA_LLENOS_GP_VD;
    private String CWSF_CARGA_VACIOS_GB_VI;
    private String CWSF_CARGA_VACIOS_GB_VD;
    private String CWSF_CARGA_VACIOS_GP_VI;
    private String CWSF_CARGA_VACIOS_GP_VD;
    private String CWSF_DESCARGA_VEHICULOS_GB;
    private String CWSF_DESCARGA_VEHICULOS_GP;
    private String CWSF_REESTIBAS_GB;
    private String CWSF_REESTIBAS_GP;
    private String CWSF_TAPA_ESCOTILLAS_GB;
    private String CWSF_TAPA_ESCOTILLAS_GP;
    private String CWSF_DEPOSITO_TEMP_LLENO_GB;
    private String CWSF_DEPOSITO_TEMP_LLENO_GP;
    private String CWSF_DEPOSITO_TEMP_VACIO_GB;
    private String CWSF_DEPOSITO_TEMP_VACIO_GP;
    private String CWSF_REEMBARQUE_LLENO_GB;
    private String CWSF_REEMBARQUE_LLENO_GP;
    private String CWSF_REEMBARQUE_VACIO_GB;
    private String CWSF_REEMBARQUE_VACIO_GP;
    private String CWSF_DEPOSITO_MOMENT_GP;
    private String CWSF_DEPOSITO_MOMENT_GB;
    private String GRABADOR;
    private String GRABADOR_FECHA;
    private String ACTUALIZADOR;
    private String ACTUALIZADOR_FECHA;
    private String CWSF_REEMBARQUE_LLENO_RF_GP;
    private String CWSF_REEMBARQUE_LLENO_RF_GB;
    private String TON_IMPORT;
    private String TON_EXPORT;

    public BeanPorta() {
    }

}
